-- ============================================================================
-- Oracle post-load patches
-- ----------------------------------------------------------------------------
-- Adds foreign keys, unique constraints, composite indexes, and NOT NULL on
-- business-critical columns that were missing from the original loader
-- scripts. Each DDL is wrapped in a PL/SQL block that swallows the harmless
-- "already exists / already in that state" errors so the script is idempotent.
--
-- Swallowed ORA codes:
--   -955  ORA-00955: name already used by an existing object
--   -1408 ORA-01408: such column list already indexed
--   -1442 ORA-01442: column to be modified to NOT NULL is already NOT NULL
--   -2260 ORA-02260: table can have only one primary key
--   -2261 ORA-02261: such unique or primary key already exists
--   -2275 ORA-02275: such a referential constraint already exists in the table
--
-- Targets:
--   PORTFOLIO_MGMT  (load_portfolio_mgmt.py — Altavest)
--   CLAIMS_MART     (load_claims_mart.py    — Verity)
-- ============================================================================


-- ════════════════════════════════════════════════════════════════════════════
-- PORTFOLIO_MGMT (Altavest)
-- ════════════════════════════════════════════════════════════════════════════

-- ── NOT NULL on business-critical columns ───────────────────────────────────
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PORTFOLIO_MGMT.HOLDINGS MODIFY (PORTFOLIO_ID NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1442) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PORTFOLIO_MGMT.HOLDINGS MODIFY (INSTRUMENT_ID NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1442) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PORTFOLIO_MGMT.HOLDINGS MODIFY (AS_OF NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1442) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PORTFOLIO_MGMT.NAV_DAILY MODIFY (PORTFOLIO_ID NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1442) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PORTFOLIO_MGMT.NAV_DAILY MODIFY (AS_OF NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1442) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PORTFOLIO_MGMT.PERFORMANCE_RETURNS MODIFY (PORTFOLIO_ID NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1442) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PORTFOLIO_MGMT.PERFORMANCE_RETURNS MODIFY (BENCHMARK_ID NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1442) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PORTFOLIO_MGMT.MANDATES MODIFY (PORTFOLIO_ID NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1442) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PORTFOLIO_MGMT.VALUATION_AUDIT MODIFY (PORTFOLIO_ID NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1442) THEN RAISE; END IF;
END;
/

-- ── Foreign keys (Fivetran picks these up for destination-side hints) ───────
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PORTFOLIO_MGMT.HOLDINGS ADD CONSTRAINT FK_HOLDINGS_PORTFOLIO FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIO_MGMT.PORTFOLIOS(PORTFOLIO_ID)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2275, -2261) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PORTFOLIO_MGMT.HOLDINGS ADD CONSTRAINT FK_HOLDINGS_INSTRUMENT FOREIGN KEY (INSTRUMENT_ID) REFERENCES PORTFOLIO_MGMT.INSTRUMENTS(INSTRUMENT_ID)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2275, -2261) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PORTFOLIO_MGMT.NAV_DAILY ADD CONSTRAINT FK_NAV_DAILY_PORTFOLIO FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIO_MGMT.PORTFOLIOS(PORTFOLIO_ID)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2275, -2261) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PORTFOLIO_MGMT.PERFORMANCE_RETURNS ADD CONSTRAINT FK_PERF_PORTFOLIO FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIO_MGMT.PORTFOLIOS(PORTFOLIO_ID)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2275, -2261) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PORTFOLIO_MGMT.PERFORMANCE_RETURNS ADD CONSTRAINT FK_PERF_BENCHMARK FOREIGN KEY (BENCHMARK_ID) REFERENCES PORTFOLIO_MGMT.BENCHMARKS(BENCHMARK_ID)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2275, -2261) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PORTFOLIO_MGMT.MANDATES ADD CONSTRAINT FK_MANDATES_PORTFOLIO FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIO_MGMT.PORTFOLIOS(PORTFOLIO_ID)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2275, -2261) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PORTFOLIO_MGMT.VALUATION_AUDIT ADD CONSTRAINT FK_VALAUDIT_PORTFOLIO FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIO_MGMT.PORTFOLIOS(PORTFOLIO_ID)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2275, -2261) THEN RAISE; END IF;
END;
/

-- ── Unique constraints on natural keys ──────────────────────────────────────
BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX PORTFOLIO_MGMT.UQ_HOLDINGS_ASOF_PORT_INST ON PORTFOLIO_MGMT.HOLDINGS (AS_OF, PORTFOLIO_ID, INSTRUMENT_ID)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX PORTFOLIO_MGMT.UQ_NAV_DAILY_ASOF_PORT ON PORTFOLIO_MGMT.NAV_DAILY (AS_OF, PORTFOLIO_ID)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX PORTFOLIO_MGMT.UQ_PORTFOLIOS_CODE ON PORTFOLIO_MGMT.PORTFOLIOS (PORTFOLIO_CODE)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX PORTFOLIO_MGMT.UQ_BENCHMARKS_CODE ON PORTFOLIO_MGMT.BENCHMARKS (BENCHMARK_CODE)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

-- ── Composite index for HOLDINGS (AS_OF, PORTFOLIO_ID) queries ──────────────
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX PORTFOLIO_MGMT.IX_HOLDINGS_ASOF_PORT ON PORTFOLIO_MGMT.HOLDINGS (AS_OF, PORTFOLIO_ID)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/


-- ════════════════════════════════════════════════════════════════════════════
-- CLAIMS_MART (Verity)
-- ════════════════════════════════════════════════════════════════════════════

-- ── NOT NULL on business-critical columns ───────────────────────────────────
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS_MART.CLAIMS MODIFY (CLAIM_NUMBER NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1442) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS_MART.CLAIMS MODIFY (POLICY_NUMBER NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1442) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS_MART.CLAIMS MODIFY (DATE_OF_LOSS NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1442) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS_MART.CLAIMS MODIFY (PERIL_CODE NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1442) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS_MART.CLAIMS MODIFY (STATUS_CODE NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1442) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS_MART.CLAIM_PAYMENTS MODIFY (CLAIM_ID NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1442) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS_MART.CLAIM_RESERVES_HISTORY MODIFY (CLAIM_ID NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1442) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS_MART.CLAIM_NOTES MODIFY (CLAIM_ID NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1442) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS_MART.SUBROGATION_RECOVERIES MODIFY (CLAIM_ID NOT NULL)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-1442) THEN RAISE; END IF;
END;
/

-- ── Foreign keys ────────────────────────────────────────────────────────────
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS_MART.CLAIMS ADD CONSTRAINT FK_CLAIMS_PERIL FOREIGN KEY (PERIL_CODE) REFERENCES CLAIMS_MART.PERIL_TYPES(PERIL_CODE)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2275, -2261) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS_MART.CLAIMS ADD CONSTRAINT FK_CLAIMS_STATUS FOREIGN KEY (STATUS_CODE) REFERENCES CLAIMS_MART.CLAIM_STATUSES(STATUS_CODE)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2275, -2261) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS_MART.CLAIMS ADD CONSTRAINT FK_CLAIMS_ADJUSTER FOREIGN KEY (ADJUSTER_ID) REFERENCES CLAIMS_MART.ADJUSTERS(ADJUSTER_ID)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2275, -2261) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS_MART.CLAIM_PAYMENTS ADD CONSTRAINT FK_PAYMENTS_CLAIM FOREIGN KEY (CLAIM_ID) REFERENCES CLAIMS_MART.CLAIMS(CLAIM_ID)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2275, -2261) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS_MART.CLAIM_RESERVES_HISTORY ADD CONSTRAINT FK_RESERVES_CLAIM FOREIGN KEY (CLAIM_ID) REFERENCES CLAIMS_MART.CLAIMS(CLAIM_ID)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2275, -2261) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS_MART.CLAIM_RESERVES_HISTORY ADD CONSTRAINT FK_RESERVES_ADJUSTER FOREIGN KEY (ADJUSTER_ID) REFERENCES CLAIMS_MART.ADJUSTERS(ADJUSTER_ID)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2275, -2261) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS_MART.CLAIM_NOTES ADD CONSTRAINT FK_NOTES_CLAIM FOREIGN KEY (CLAIM_ID) REFERENCES CLAIMS_MART.CLAIMS(CLAIM_ID)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2275, -2261) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS_MART.SUBROGATION_RECOVERIES ADD CONSTRAINT FK_SUBRO_CLAIM FOREIGN KEY (CLAIM_ID) REFERENCES CLAIMS_MART.CLAIMS(CLAIM_ID)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-2275, -2261) THEN RAISE; END IF;
END;
/

-- ── Unique constraints on natural keys ──────────────────────────────────────
BEGIN
  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX CLAIMS_MART.UQ_CLAIMS_CLAIM_NUMBER ON CLAIMS_MART.CLAIMS (CLAIM_NUMBER)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

-- ── Composite indexes for common time-series and rollup queries ─────────────
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX CLAIMS_MART.IX_CLAIMS_DOL_STATUS ON CLAIMS_MART.CLAIMS (DATE_OF_LOSS, STATUS_CODE)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX CLAIMS_MART.IX_PAYMENTS_CLAIM_DATE ON CLAIMS_MART.CLAIM_PAYMENTS (CLAIM_ID, PAYMENT_DATE)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX CLAIMS_MART.IX_RESERVES_CLAIM_ASOF ON CLAIMS_MART.CLAIM_RESERVES_HISTORY (CLAIM_ID, AS_OF)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF;
END;
/

-- ============================================================================
-- end of Oracle post-load patches
-- ============================================================================
